# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - brajesh

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_607dc8f0026e4afbbd71a869942f263d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_17da2b22954a4883aa7347ccc4c29232 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_607dc8f0026e4afbbd71a869942f263d }}/appsvc/wordpress-alpine-php:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'brajesh'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9ed74d7cce3e4bd7a37eda141f1e7cf3 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_607dc8f0026e4afbbd71a869942f263d }}/appsvc/wordpress-alpine-php:${{ github.sha }}'